import type { Metadata } from "next";
import { Inter } from "next/font/google";  // Cambié a Inter como ejemplo
import "./globals.css";
import { CartProvider } from "./pages/context/CartContext";
import { SessionProvider } from "./pages/context/SessionContext";

const inter = Inter({
  variable: "--font-inter",  // Definir la variable para usarla
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Texas Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <SessionProvider>
          <CartProvider>
            {children}
          </CartProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
